### ISSUE TITLE
Create a perfect fake invoice for the Python invoice SDK

### ISSUE THREAD

**Issue by fakela** [mindee/documentation#366] opened 2022-03-09 01:47 UTC

**Comment by fharper** [comment] 2022-03-09 01:49
duplicate of https://github.com/mindee/devrel/issues/436

**Comment by fharper** [comment] 2022-03-09 01:49
oh, the issue I wanted you to create is the one about updating the invoice page code examples and response once this invoice is created :)

**Closed by fharper** 2022-03-09 01:49 UTC

**Comment by fakela** [comment] 2022-03-09 01:54
Oh okay 😄

**Comment by fakela** [comment] 2022-03-09 01:55
> oh, the issue I wanted you to create is the one about updating the invoice page code examples and response once this invoice is created :)

https://github.com/mindee/documentation/issues/328 it was already created 👍
